GENERAL:
  EXP_NAME: IG-S-8
  CHECKPOINT: ./checkpoints
  LOG_DIR: ./log

TRAIN:
  LR: 1e-4
  WEIGHT_DECAY: 0.00002
  BATCH_SIZE: 32
  EPOCH: 500
  LOG_STEPS: 10
  SAVE_EPOCH: 50
  RESUME: #checkpoints/IG-S/8/model/epoch=99-step=17600.ckpt
  NUM_WORKERS: 8
  MODE: finetune
  LAST_EPOCH: 0
  LAST_ITER: 0
