GENERAL:
  EXP_NAME: Phase-2
  CHECKPOINT: ./checkpoints
  LOG_DIR: ./log

TRAIN:
  LR: 1e-5
  WEIGHT_DECAY: 0.00002
  BATCH_SIZE: 20
  EPOCH: 500
  LOG_STEPS: 10
  SAVE_EPOCH: 50
  RESUME: /mnt/user/chenjianqi/code/HHInter/checkpoints/Phase-1.ckpt
  NUM_WORKERS: 10
  MODE: finetune
  LAST_EPOCH: 0
  LAST_ITER: 0
